version: "3.9"

services:
  ingest:
    build: .
    env_file: .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - chroma_store:/app/.chroma
    command: >
      python -m scripts.ingest_pdf data/RENTA_2024.pdf

  backend:
    build: .
    env_file: .env
    command: uvicorn rag.api:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - chroma_store:/app/.chroma

  frontend:
    build: .
    env_file: .env
    command: streamlit run frontend/streamlit_app.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - chroma_store:/app/.chroma

volumes:
  chroma_store:
