FROM python:3.11-slim

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential gcc && \
    pip install -r requirements.txt && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8501

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.address=0.0.0.0"]