services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/manuelescola/GenAI_IRPF_chatbot
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: backend
    env: docker
    repo: https://github.com/manuelescola/GenAI_IRPF_chatbot
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false
